### ISSUE TITLE
20231004 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [wntjdals0214/c202309#1]
워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 6]
         - 이유: main의 반환값은 int 여야 합니다
         - 해결: void main()을 int main()으로 변경하고 마지막에 return 0;을 추가하세요.
    - Warning: format specifies type 'int' but the argument has type 'long' [line 9]
    - Warning: format specifies type 'int' but the argument has type 'long' [line 10]
    - Warning: format specifies type 'int' but the argument has type 'long' [line 11]
        - 이유: 서식지정자 %d는 int 데이터를 위한 지정자입니다
        - 해결: %d를 %ld로 바꾸세요
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 6]
         - 이유: main의 반환값은 int 여야 합니다
         - 해결: void main()을 int main()으로 변경하고 마지막에 return 0;을 추가하세요.

**Comment by wntjdals0214** [comment]
수정했습니다.
