### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [wntjdals0214/c202309#2]
### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week3/do-while_even
    - 추출된 주석: i 가   짝 수 이 면   반 복 문   처 음 으 로
- Insufficient comments in challenge/week3/while_even
    - 추출된 주석: i 가   짝 수 이 면   반 복 문   처 음 으 로

**Comment by wntjdals0214** [comment]
해결했습니다.
